blueprint:
  name: "Remote to Timer: Full Cycle"
  description: >
    Press a button to start a timer, and define actions for both the start and end of that timer.
  domain: automation
  input:
    remote_device:
      name: Remote Device
      description: The MQTT remote that triggers the timer.
      selector:
        device:
          integration: mqtt
          multiple: false
    
    remote_subtype:
      name: Remote Button Action
      description: "e.g., 1_double, 2_single, etc."
      default: "1_double"

    target_timer:
      name: Timer Entity
      description: Select the timer to start and monitor.
      selector:
        entity:
          domain: timer

    # --- Actions ---
    timer_start_actions:
      name: "Actions on Start"
      description: Triggered when the button is pressed and timer starts.
      default: []
      selector:
        action: {}

    timer_end_actions:
      name: "Actions on End"
      description: Triggered when the timer finishes or is stopped.
      default: []
      selector:
        action: {}

mode: restart

trigger:
  # 1. Trigger from Remote
  - domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: !input remote_subtype
    trigger: device
    id: "remote_pressed"
  
  # 2. Trigger when Timer finishes
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input target_timer
    id: "timer_ended"

  # 3. Trigger if Timer is manually stopped
  - platform: state
    entity_id: !input target_timer
    from: "active"
    to: "idle"
    id: "timer_ended"

action:
  - choose:
      # BUTTON PRESSED -> START TIMER + START ACTIONS
      - conditions:
          - condition: trigger
            id: "remote_pressed"
        sequence:
          - action: timer.start
            target:
              entity_id: !input target_timer
          - sequence: !input timer_start_actions

      # TIMER FINISHED -> END ACTIONS
      - conditions:
          - condition: trigger
            id: "timer_ended"
        sequence: !input timer_end_actions